config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :users, only: [:new, :create] do
    member do
      get :activate
    end
  end
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'register' => 'users#new', as: :register
  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout

  resources :thoughts, only: [:create]

  get 'diary' => 'users#diary'
  get 'explore' => 'thoughts#explore'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/thought.rb
class Thought < ApplicationRecord

  belongs_to :user

  validates :user, presence: true
  validate :user_publish_once_a_day_only

  scope :created_after, -> (datetime) {
    where('? <= created_at', datetime)
  }
  scope :explorable, -> {
    where(is_public: true)
  }

  alias_attribute :public?, :is_public

private

  def user_publish_once_a_day_only
    thought = user.published_on(created_at || DateTime.current).take
    if thought and thought.id != id
      errors.add(:base, 'Thought can be published once a day only')
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :thoughts

  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true

  def published_today?
    published_on(DateTime.current).count > 0
  end

  def published_on(date)
    thoughts.where('? <= created_at AND created_at <= ?', date.beginning_of_day, date.end_of_day)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :require_login

  def require_not_logged
    redirect_to diary_path if current_user
  end

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  before_action :require_not_logged
  skip_before_action :require_login

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user
      @user.deliver_reset_password_instructions!
      redirect_to root_path, notice: 'Les instructions pour la réinitialisation de votre mot de passe ont été envoyées par email.'
    else
      redirect_to new_password_reset_path, alert: 'Aucun utilisateur ne semble correspondre à cette adresse email.'
    end
  end

  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)

    if @user.blank?
      redirect_to root_path
    end
  end

  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)

    if @user.blank?
      redirect_to root_path
      return
    end

    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.change_password!(params[:user][:password])
      redirect_to login_path, notice: 'Le mot de passe a été correctement réinitialisé.'
    else
      redirect_to :back, alert: @user.errors.full_messages.first
    end
  end
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController

  def explore
    @thoughts = Thought.explorable
                       .created_after(24.hours.ago)
                       .order('created_at DESC')
  end

  def create
    thought = Thought.new(create_thought_params)

    if thought.save
      redirect_to diary_path, notice: 'Votre pensée vient d’être publiée.'
    else
      redirect_to diary_path, alert: 'Votre pensée n’a pas pu être publiée.'
    end
  end

private

  def create_thought_params
    params.require(:thought).permit(:content, :is_public)
                            .merge(user: current_user)
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  before_action :require_not_logged, except: [:destroy]
  skip_before_action :require_login

  def new
  end

  def create
    user = login(params[:email], params[:password], params[:remember])
    if user
      redirect_to diary_path, notice: 'Vous êtes désormais connecté.'
    else
      redirect_to login_path, alert: 'La connexion a échoué. Êtes-vous sûr de vos identifiants ?'
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: 'Vous êtes désormais déconnecté.'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_not_logged, only: [:new, :create, :activate]
  skip_before_action :require_login, only: [:new, :create, :activate]

  def diary
    @thoughts = current_user.thoughts.order('created_at DESC')
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(create_user_params)
    if @user.save
      redirect_to root_path, notice: "Un mail de confirmation vous a été envoyé à l’adresse #{ @user.email }"
    else
      redirect_to register_path, alert: @user.errors.full_messages.first
    end
  end

  def activate
    user = User.load_from_activation_token(params[:id])
    if user
      user.activate!
      redirect_to login_path, notice: 'Votre compte a été validé, vous pouvez désormais vous connecter.'
    else
      redirect_to root_path
    end
  end

private

  def create_user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_action :require_not_logged
  skip_before_action :require_login

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taglibro</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="app">
    <div class="app-header">
      <div class="container">
        <div class="row">
          <%= link_to 'Taglibro', root_path %>
          <div class="row-extend"></div>
          <% if current_user %>
            <div><%= current_user.email %> (<%= link_to 'Déconnexion', logout_path, method: :post %>)</div>
          <% end %>
        </div>
      </div>
    </div>

    <% if notice or alert %>
      <div class="app-notifications">
        <%- if notice %>
          <div class="notification-notice">
            <div class="container">
              <%= notice %>
            </div>
          </div>
        <% end %>
        <%- if alert %>
          <div class="notification-alert">
            <div class="container">
              <%= alert %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

    <div class="app-content">
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/password_resets/edit.html.erb
<div class="panel">
  <h1>Réinitialisation de votre mot de passe</h1>

  <%= form_for @user, url: password_reset_path(@token), method: :put do |f| %>

    <% if @user.errors.any? %>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %>
        <% end %>
      </ul>
    <% end %>

    <div class="form-group form-group-static">
      <%= f.label :email %>
      <%= @user.email %>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>

    <div class="form-group form-group-actions">
      <%= f.submit 'Modifier', class: 'btn btn-primary' %>
      <%= link_to 'Annuler', login_path, class: 'btn btn-link' %>
    </div>

  <% end %>
</div>

app/views/password_resets/new.html.erb
<div class="panel">
  <h1>Réinitialisation du mot de passe</h1>

  <%= form_tag password_resets_path, method: :post do %>

    <div class="form-group">
      <%= label_tag :email %><br />
      <%= text_field_tag :email, params[:email] %>
    </div>

    <div class="form-group form-group-actions">
      <%= submit_tag 'Réinitialiser', class: 'btn btn-primary' %>
      <%= link_to 'Annuler', login_path, class: 'btn btn-link' %>
    </div>

  <% end %>
</div>

app/views/thoughts/_navigation.html.erb
<div class="thoughts-navigation">
  <%= link_to 'Journal', diary_path, class: action_name == 'diary' ? 'active' : '' %>
  <%= link_to 'Explorer', explore_path, class: action_name == 'explore' ? 'active' : '' %>
</div>

app/views/thoughts/_thought.html.erb
<div class="thought">
  <div class="thought-content"><%= thought.content %></div>

  <div class="row">
    <div class="row-extend thought-created-at">
      Le <%= I18n.l thought.created_at, format: :long %>.
    </div>

    <div class="thought-visibility">
      <% if thought.public? %>
        <%= icon('unlock', 'Public') %>
      <% else %>
        <%= icon('lock', 'Privé') %>
      <% end %>
    </div>
  </div>
</div>

app/views/thoughts/explore.html.erb
<%= render 'thoughts/navigation' %>

<div class="explore">
  <% if @thoughts.empty? %>
    <div class="thoughts-placeholder">
      Personne n'a rien publié ces dernières 24 heures, et vous&nbsp;?
    </div>
  <% end %>
  <%= render @thoughts %>
</div>

app/views/user_sessions/new.html.erb
<div class="panel">
  <h1>Connexion</h1>

  <%= form_tag user_sessions_path, method: :post do %>

    <div class="form-group">
      <%= label_tag :email, 'Email' %>
      <%= text_field_tag :email, params[:email] %>
    </div>

    <div class="form-group">
      <%= label_tag :password, 'Mot de passe' %>
      <%= password_field_tag :password, params[:password] %>
    </div>

    <div class="form-group form-group-checkbox">
      <div class="checkbox-container">
        <%= check_box_tag :remember, params[:remember], true %>
        <%= label_tag :remember, 'Rester connecté' %>
      </div>
    </div>

    <div class="form-group form-group-actions">
      <%= submit_tag 'Se connecter', class: 'btn btn-primary' %>
      <%= link_to 'Vous n’avez pas de compte ?', register_path, class: 'btn btn-link' %>
    </div>

    <div class="form-group form-group-actions">
      <%= link_to 'Vous avez oublié votre mot de passe ?', new_password_reset_path, class: 'btn btn-link' %>
    </div>

  <% end %>
</div>

app/views/users/diary.html.erb
<%= render 'thoughts/navigation' %>

<div class="diary">
  <% if current_user.published_today? %>
    <div class="publisher publisher-placeholder">
      Vous ne pouvez publier qu'une fois par jour. Revenez demain&nbsp;!
    </div>
  <% else %>
    <%= form_for :thought, url: thoughts_path, html: { class: 'publisher' } do |f| %>
      <div class="publisher-content">
        <%= f.text_area :content, placeholder: 'Qu’avez-vous pensé de votre journée ?' %>
      </div>

      <div class="row publisher-bottom-bar">
        <div class="checkbox-container">
          <%= f.check_box :is_public %>
          <%= f.label :is_public, 'Public ?' %>
        </div>

        <div class="row-extend"></div>

        <%= f.submit 'Publier', class: 'btn btn-primary' %>
      </div>
    <% end %>
  <% end %>

  <% if @thoughts.empty? %>
    <div class="thoughts-placeholder">
      Vous n'avez rien publié pour le moment.
    </div>
  <% end %>
  <%= render @thoughts %>
</div>

app/views/users/new.html.erb
<div class="panel">
  <h1>Inscription</h1>

  <%= form_for :user, url: users_path do |f| %>

    <% if @user.errors.any? %>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %>
        <% end %>
      </ul>
    <% end %>

    <div class="form-group">
      <%= f.label :email%>
      <%= f.text_field :email %>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>

    <div class="form-group form-group-actions">
      <%= f.submit 'S’inscrire', class: 'btn btn-primary' %>
      <%= link_to 'Vous avez déjà un compte ?', login_path, class: 'btn btn-link' %>
    </div>

  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="panel">
  <h1>Bienvenue sur Taglibro !</h1>

  <div>
    <%= link_to 'Inscrivez-vous', register_path %>
    ou <%= link_to 'connectez-vous', login_path %>
  </div>
</div>